version: "3.9"
services:
  db:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: afsoh
      MYSQL_USER: afsoh
      MYSQL_PASSWORD: afsoh
      MYSQL_ROOT_PASSWORD: secret
