services:
  web:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: afsoh
      MYSQL_USER: afsoh
      MYSQL_PASSWORD: afsoh
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql

  pma:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  dbdata: