version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: afsoh_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: afsoh_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: afsoh_db
      MYSQL_USER: afsoh_user
      MYSQL_PASSWORD: afsoh_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  db_data:
